spring.application.name=ragscan

spring.main.web-application-type=none
server.port=9090

spring.shell.interactive.enabled=true
spring.shell.script.enabled=true

spring.threads.virtual.enabled=true

spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=ragscan
spring.ai.vectorstore.qdrant.initialize-schema=true

spring.ai.openai.api-key=${GOOGLE_API_KEY}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.chat.options.model=gemini-2.0-flash
spring.ai.openai.chat.completions-path=/v1beta/openai/chat/completions

spring.ai.openai.embedding.api-key=${GOOGLE_API_KEY}
spring.ai.openai.embedding.base-url=https://generativelanguage.googleapis.com
spring.ai.openai.embedding.embeddings-path=/v1beta/openai/embeddings
spring.ai.openai.embedding.options.model=gemini-embedding-exp-03-07
spring.ai.openai.embedding.options.dimensions=768