name: Build Ragscan with GraalVM
on: [push, pull_request]
jobs:
  build:
    name: Ragscan on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '22'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build Ragscan
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          mvn -X -Pnative native:compile -DskipTests
#      - name: Compile with maven
#        run: mvn -X -Pnative native:compile -DskipTests

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ragscan-${{ matrix.os }}
          path: ragscan*